wolfrollapp/urls.py
from django.urls import path

from . import views

app_name = "wolfrollapp"
urlpatterns = [
	path('login/', views.loginPage, name="loginPage"),
	path('logout/', views.logoutPage, name="logoutPage"),
	path('register/', views.registerPage, name="registerPage"),
	path('', views.home, name="home"),
	path('create/', views.createPlayer, name="createPlayer"),
	path('delete/<str:pk>', views.deletePlayer, name="deletePlayer"),
	path('roles/', views.viewRoles, name="viewRoles"),
	path('rolesedit/', views.editRoles, name="editRoles"),
	path('create_role/', views.createRole, name="createRole"),
	path('remove_role/<str:title>', views.deleteRole, name="deleteRole"),
	path('toggle_role_pref/<str:key>', views.updateRoleToggle, name="updateRoleToggle"),
	path('reset_params/', views.resetParams, name="resetParams"),
	path('increase_wolf_count/', views.increaseWolfCount, name="increaseWolfCount"),
	path('decrease_wolf_count/', views.decreaseWolfCount, name="decreaseWolfCount"),
	path('increase_balance_goal/', views.increaseBalanceGoal, name="increaseBalanceGoal"),
	path('decrease_balance_goal/', views.decreaseBalanceGoal, name="decreaseBalanceGoal"),
	path('roll_game/', views.rollGame, name="rollGame"),
	path('update_lock/<str:pk>', views.updateLock, name="updateLock"),
	path('increase_player_count/', views.increasePlayerCount, name="increasePlayerCount"),
	path('decrease_player_count/', views.decreasePlayerCount, name="decreasePlayerCount"),
	path('speed_roller/', views.speedRollerHome, name="speedRollerHome"),
	path('speed_roll/', views.speedRoll, name="speedRoll"),
	path('save_game/<str:title>', views.saveGame, name="saveGame"),
	path('roll_from_saved/<str:pk>', views.rollFromSaved, name="rollFromSaved"),
]

wolfrollsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wolfrollapp.urls')),
]

wolfrollapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Player(models.Model):
	name = models.CharField(max_length=50)
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="player", null=True, blank=True)

	def __str__(self):
		return self.name


class Role(models.Model):
	score = models.IntegerField()
	title = models.CharField(max_length=40)
	description = models.CharField(max_length=400)
	alignment = models.CharField(max_length=20)
	type = models.CharField(max_length=20)
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="role_user", null=True, blank=True)

	def __str__(self):
		return self.title


class GameParameters(models.Model):
	preferences = models.JSONField()
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_prefs", null=True, blank=True)


class SavedGame(models.Model):
	name = models.CharField(max_length=200)
	roles = models.JSONField()
	player_count = models.IntegerField(default=7)
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_saved_games", null=True, blank=True)

	def __str__(self):
		return self.name

class RoleAssignment(models.Model):
	role = models.ForeignKey(Role, on_delete=models.CASCADE, related_name="temp_role", null=True)
	player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name="temp_player", null=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="assignment_user", null=True)
	locked = models.BooleanField(default=False)

wolfrollapp/forms.py
from django.forms import ModelForm
from django import forms
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Player, Role


class RoleForm(ModelForm):
	class Meta:
		model = Role
		fields = ['title', 'score', 'description', 'alignment', 'type']


class PlayerForm(ModelForm):

	name = forms.CharField(
		max_length=255,
		widget=forms.TextInput(attrs={'autofocus': True})
	)

	class Meta:
		model = Player
		fields = ['name']


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

wolfrollapp/views.py
import json
import pandas
import random
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import CreateUserForm, PlayerForm, RoleForm
from .models import Player, Role, GameParameters, RoleAssignment, SavedGame


# Create your views here.
class Game:
    def __init__(self, roles, score, title):
        self.roles = roles
        self.score = score
        self.title = title


@login_required(login_url='/login')
def home(request):
    player_form = PlayerForm()
    player_list = Player.objects.filter(user=request.user)
    if not Role.objects.filter(user=request.user):
        df = pandas.read_csv('basicroles.csv')
        for index, row in df.iterrows():
            row = Role(
                score=row['role_score'],
                title=row['role_title'],
                description=row['role_description'],
                alignment=row['role_alignment'],
                type=row['role_type'],
                user=request.user
            )
            row.save()

        j = {key: True for key in
             Role.objects.filter(user=request.user).order_by().values_list('type', flat=True).distinct()}
        initial_prefs = {
            'typePref': j,
            'wolfCount': 2,
            'balanceGoal': 0,
            'playerCount': 7,
            'games_dict': {},
        }
        initial_prefs = json.dumps(initial_prefs)
        preferences = GameParameters(preferences=initial_prefs, user=request.user)
        preferences.save()

    game_params = GameParameters.objects.get(user=request.user)
    game_params_dict = json.loads(game_params.preferences)
    role_type_toggles = game_params_dict['typePref']
    wolf_count = game_params_dict['wolfCount']
    balance_goal = game_params_dict['balanceGoal']

    role_assignments = RoleAssignment.objects.filter(user=request.user)
    game_score = sum([i.role.score for i in role_assignments])
    player_list = Player.objects.filter(user=request.user)
    available_saved_games = SavedGame.objects.filter(user=request.user).filter(player_count=len(player_list))
    context = {
        'player_form': player_form,
        'player_list': player_list,
        'role_type_toggles': role_type_toggles,
        'wolf_count': wolf_count,
        'balance_goal': balance_goal,
        'role_assignments': role_assignments,
        'game_score': game_score,
        'available_saved_games': available_saved_games,
    }
    return render(request, 'wolfrollapp/home.html', context)


def speedRollerHome(request):
    game_params = GameParameters.objects.get(user=request.user)
    game_params_dict = json.loads(game_params.preferences)
    role_type_toggles = game_params_dict['typePref']
    wolf_count = game_params_dict['wolfCount']
    balance_goal = game_params_dict['balanceGoal']
    player_count = game_params_dict['playerCount']
    games_dict = game_params_dict['games_dict']

    games_list = []
    for key in games_dict:
        new_game = Game(roles=games_dict[key]['roles'], score=games_dict[key]['score'], title=key)
        games_list.append(new_game)

    all_saved_games = SavedGame.objects.filter(user=request.user)

    context = {
        'role_type_toggles': role_type_toggles,
        'wolf_count': wolf_count,
        'balance_goal': balance_goal,
        'player_count': player_count,
        'games_dict': games_dict,
        'games_list': games_list,
        'all_saved_games': all_saved_games,
    }
    return render(request, 'wolfrollapp/speedRoller.html', context)


def speedRoll(request):
    game_params = GameParameters.objects.get(user=request.user)
    game_params_dict = json.loads(game_params.preferences)
    role_type_toggles = game_params_dict['typePref']
    wolf_count = game_params_dict['wolfCount']
    balance_goal = game_params_dict['balanceGoal']
    player_count = game_params_dict['playerCount']
    games_dict = game_params_dict['games_dict']

    wolf_roles = Role.objects.filter(user=request.user, type="Wolf")
    available_types = [key for key in role_type_toggles if role_type_toggles[key]]
    available_roles = Role.objects.filter(user=request.user, type__in=available_types)
    new_games_dict = {}
    for i in range(5):
        roles_list = []
        for wolf in range(wolf_count):
            roles_list.append(random.choice(wolf_roles))
        while player_count > len(roles_list):
            if sum([i.score for i in roles_list]) > balance_goal:
                roles_list.append(random.choice([i for i in available_roles if i.score < 0 and i.alignment == 'Town']))
            elif sum([i.score for i in roles_list]) <= balance_goal:
                roles_list.append(random.choice([i for i in available_roles if i.score >= 0]))
        game_score = sum([i.score for i in roles_list])
        new_games_dict['Game ' + str(i+1)] = {'roles': [i.title for i in roles_list], 'score': game_score}
    new_prefs = {
        'typePref': role_type_toggles,
        'wolfCount': wolf_count,
        'balanceGoal': balance_goal,
        'playerCount': player_count,
        'games_dict': new_games_dict,
    }
    j = json.dumps(new_prefs)
    GameParameters.objects.filter(user=request.user).update(preferences=j)
    print(new_games_dict)
    return redirect('wolfrollapp:speedRollerHome')


def saveGame(request, title):
    try:
        print("trying")
        SavedGame.objects.filter(user=request.user).get(name=request.POST.get('name'))
        print("got it")
        messages.warning(request, "You have already used that name! Choose a new name!")
    except SavedGame.DoesNotExist:
        game_params = GameParameters.objects.get(user=request.user)
        game_params_dict = json.loads(game_params.preferences)
        player_count = game_params_dict['playerCount']
        roles_list = json.dumps(game_params_dict['games_dict'][title])
        new_saved_game = SavedGame(name=request.POST.get('name'), roles=roles_list, user=request.user, player_count=player_count)
        new_saved_game.save()

    return redirect('wolfrollapp:speedRollerHome')


def rollGame(request):
    game_params = GameParameters.objects.get(user=request.user)
    game_params_dict = json.loads(game_params.preferences)
    role_type_toggles = game_params_dict['typePref']
    wolf_count = game_params_dict['wolfCount']
    balance_goal = game_params_dict['balanceGoal']


    player_list = Player.objects.filter(user=request.user)

    wolf_roles = Role.objects.filter(user=request.user, type="Wolf")
    available_types = [key for key in role_type_toggles if role_type_toggles[key]]
    available_roles = Role.objects.filter(user=request.user, type__in=available_types)

    # reset assignments
    RoleAssignment.objects.filter(user=request.user, locked=False).delete()
    locked_game = RoleAssignment.objects.filter(user=request.user)
    roles_list = []
    locked_roles = []
    for i in locked_game:
        roles_list.append(Role.objects.filter(user=request.user, title=i.role.title).get())
        locked_roles.append(Role.objects.filter(user=request.user, title=i.role.title).get())

    revised_wolf_count = wolf_count - len([i for i in roles_list if i.type == "Wolf"])

    RoleAssignment.objects.filter(user=request.user).delete()

    for i in range(revised_wolf_count):
        roles_list.append(random.choice(wolf_roles))

    while len(player_list) > len(roles_list):
        game_score = 0
        for i in roles_list:
            game_score += i.score
        if game_score > balance_goal:
            roles_list.append(random.choice([i for i in available_roles if i.score < 0 and i.alignment == 'Town']))
        elif game_score <= balance_goal:
            roles_list.append(random.choice([i for i in available_roles if i.score >= 0]))

    game_score = 0
    for i in roles_list:
        game_score += i.score
    random.shuffle(roles_list)
    random.shuffle(list(player_list))
    for i in range(len(roles_list)):
        assignment = RoleAssignment(
            player=player_list[i],
            role=roles_list[i],
            locked=True if roles_list[i] in locked_roles else False,
            user=request.user,
        )
        assignment.save()
    return redirect('wolfrollapp:home')


def rollFromSaved(request, pk):
    RoleAssignment.objects.filter(user=request.user).delete()
    player_list = Player.objects.filter(user=request.user)
    roles_list = json.loads(SavedGame.objects.get(id=pk).roles)['roles']

    random.shuffle(roles_list)
    random.shuffle(list(player_list))
    for i in range(len(roles_list)):
        print(roles_list[i])
        assignment = RoleAssignment(
            player=player_list[i],
            role=Role.objects.filter(user=request.user).get(title=roles_list[i]),
            locked=False,
            user=request.user,
        )
        assignment.save()
    return redirect('wolfrollapp:home')


def updateLock(request, pk):
    assignment = RoleAssignment.objects.get(id=pk)
    if assignment.locked:
        RoleAssignment.objects.filter(id=pk).update(locked=False)
    else:
        RoleAssignment.objects.filter(id=pk).update(locked=True)
    return redirect('wolfrollapp:home')


def updateRoleToggle(request, key):
    game_params = GameParameters.objects.get(user=request.user)
    game_params_dict = json.loads(game_params.preferences)
    role_type_toggles = game_params_dict['typePref']
    wolf_count = game_params_dict['wolfCount']
    balance_goal = game_params_dict['balanceGoal']
    player_count = game_params_dict['playerCount']
    games_dict = game_params_dict['games_dict']

    if role_type_toggles[key]:
        role_type_toggles[key] = False
    else:
        role_type_toggles[key] = True
    new_prefs = {
        'typePref': role_type_toggles,
        'wolfCount': wolf_count,
        'balanceGoal': balance_goal,
        'playerCount': player_count,
        'games_dict': games_dict
    }

wolfrollapp/templates/wolfrollapp/home.html
{%  extends 'wolfrollapp/main.html' %}
{% block content %}
<div style="padding-left: 3%; top: 1.5%; position: relative; float: left; width: 17%">
<h1>Role Types:</h1>
<table style="width:100%">
    {% for key, value in role_type_toggles.items %}
        {% if value %}
            <tr>
                <td>
                    <form method="POST" action="{% url 'wolfrollapp:updateRoleToggle' key %}">
                        {% csrf_token %}
                        <button style="vertical-align: center; padding: 8px; background: cadetblue; border-radius: 40px; float: right" type="submit"></button></form>
                </td>
                <td style="color:blanchedalmond">{{ key }}</td>

            </tr>

        {% else %}
            <tr>
                <td>
                    <form method="POST" action="{% url 'wolfrollapp:updateRoleToggle' key %}">
                        {% csrf_token %}
                        <button style="vertical-align: center; padding: 8px; background: darkred; border-radius: 40px; float: right" type="submit"></button></form>
                </td>
                <td style="color: gray"><strike>{{ key }}</strike></td>

            </tr>
        {% endif %}
    {% endfor %}
</table>
<h2 style="color: blanchedalmond">Werewolf Count:</h2>
<table style="margin-left: auto; margin-right: auto">
    <tr>
        <td>
            <form method="POST" action="{% url 'wolfrollapp:decreaseWolfCount' %}">
                {% csrf_token %}
                <button style="vertical-align: center; padding: 8px; background: darkred; border-radius: 40px;font-size: 15px;  float: right" type="submit">-</button>
            </form>
        </td>
        <td>
            <h1 style="font-size: 50px; padding-inline: 15px">{{ wolf_count }}</h1>
        </td>
        <td>
           <form method="POST" action="{% url 'wolfrollapp:increaseWolfCount' %}">
               {% csrf_token %}
               <button style="vertical-align: center; padding: 8px; background: cadetblue; border-radius: 40px;font-size: 15px;  float: left" type="submit">+</button>
           </form>
        </td>
    </tr>
</table>
<h2 style="color: blanchedalmond">Balance Target:</h2>
<table style="margin-left: auto; margin-right: auto">
    <tr>
        <td>
            <form method="POST" action="{% url 'wolfrollapp:decreaseBalanceGoal' %}">
                {% csrf_token %}
                <button style="vertical-align: center; padding: 8px; background: darkred; border-radius: 40px;font-size: 15px;  float: right" type="submit">-</button>
            </form>
        </td>
        <td>
            <h1 style="font-size: 50px; padding-inline: 15px">{{ balance_goal }}</h1>
        </td>
        <td>
           <form method="POST" action="{% url 'wolfrollapp:increaseBalanceGoal' %}">
               {% csrf_token %}
               <button style="vertical-align: center; padding: 8px; background: cadetblue; border-radius: 40px;font-size: 15px;  float: left" type="submit">+</button>
           </form>
        </td>
    </tr>
</table>
<table>
    <tr>
        <td>
        <form method="POST" action="{% url 'wolfrollapp:rollGame' %}">
            {% csrf_token %}
            <button style="vertical-align: center; padding: 12px 24px; background: cadetblue; border-radius: 2px; float: left; font-size: 30px; font-family: fantasy; margin-left: auto; margin-right: auto" type="submit">Roll A Game</button>
        </form>
        </td>
    </tr>

    <tr>
        <td>
            <form method="POST" action="{% url 'wolfrollapp:resetParams' %}">
                {% csrf_token %}
                <button style="vertical-align: center; padding: 12px 20px; background: slategrey; border-radius: 2px; float: left; font-size: 30px; font-family: fantasy; margin-left: auto; margin-right: auto" type="submit">Reset</button>
            </form>
        </td>
    </tr>
    <tr>
        <td>
            <a href="{% url 'wolfrollapp:speedRollerHome' %}">
                <button style="vertical-align: center; padding: 3px; background: cornsilk; border-radius: 2px; float: left; font-size: 30px; margin-left: auto; margin-right: auto" type="submit"><img src="https://ucarecdn.com/c88fb26e-9fff-4b08-a3f0-d63fa53e990c/Frost_arrowSpeedroller1.png" style="height: 60px"></button>
            </a>
        </td>
    </tr>
</table>
</div>

<div style="padding-inline: 3%; width: 25%; top: 15%; position: relative; float: left;">
    <table style="margin-left: auto; margin-right: auto;">
        {% for i in role_assignments %}
            {% if i.locked == True %}
                <tr style="border-bottom: 2px solid black">
                    <td style="padding: 20px;">{{ i.player.name }}</td>
                    <td>
                        <div class="popup" onclick="myFunction('{{ i.role.title }}')">{{ i.role.title }}
                            <span class="popuptext" id="{{ i.role.title }}">{{ i.role.description }}</span>
                        </div>
                    </td>
                    <td>
                        {% if i.role.alignment == "Evil" %}
                            <img src="https://ucarecdn.com/027f7b3a-0220-4d7f-9f9a-46d3d4b59a82/Untitleddesign.png" style="height:35px;"/>
                        {% endif %}
                    </td>
                    <td>
                        <form method="POST" action="{% url 'wolfrollapp:updateLock' i.id %}">
                            {% csrf_token %}
                            <button type="submit" style="background-color: darkred">
                                <img src="https://ucarecdn.com/f60b8c03-44c8-44c0-8f34-e52d82bc59e5/Locked.png" style="height: 55px;" />
                            </button>
                        </form>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        {% for i in role_assignments %}
            {% if i.locked == False %}
                <tr style="border-bottom: 2px solid black">
                    <td style="padding: 20px;">{{ i.player.name }}</td>
                    <td>
                        <div class="popup" onclick="myFunction('{{ i.role.title }}')">{{ i.role.title }}
                            <span class="popuptext" id="{{ i.role.title }}">{{ i.role.description }}</span>
                        </div>
                    </td>
                    <td>
                        {% if i.role.alignment == "Evil" %}
                            <img src="https://ucarecdn.com/027f7b3a-0220-4d7f-9f9a-46d3d4b59a82/Untitleddesign.png" style="height:35px;"/>
                        {% endif %}
                    </td>
                    <td>
                        <form method="POST" action="{% url 'wolfrollapp:updateLock' i.id %}">
                            {% csrf_token %}
                            <button type="submit" style="background-color: cadetblue">
                                <img src="https://ucarecdn.com/94a19923-ffde-4ef3-a3eb-d2f34fd5e390/Unlocked.png" style="height: 55px;" />
                            </button>
                        </form>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}


    </table>
<h2>Game Score: {{ game_score }}</h2>
</div>

<div style="width: 20%; top: 1.5%; position: relative; float: right;">
    <h1>Players</h1>
    <form action="{% url 'wolfrollapp:createPlayer' %}" method="POST" name="createPlayer" autofocus>
        {% csrf_token %}
        {% for field in player_form %}
            {{ field }}
        {% endfor %}
        <button style="vertical-align: center; padding: 8px 20px; background: darkseagreen; border-radius: 2px; margin-left: auto; margin-right: auto" type="submit">Add Player</button>
    </form>

    <table>
        <tr>
            <th></th>
        </tr>

        {% for player in player_list %}
        <tr>
            <td style="padding-right:30px;">{{ player }}</td>
            <td><form action="{% url 'wolfrollapp:deletePlayer' player.id %}" method="POST" name="player_delete">
                {% csrf_token %}
                <button style="vertical-align: center; padding: 8px; background: darkred; border-radius: 40px;font-size: 15px;  float: right" type="submit">X</button>
            </form>
            </td>
        </tr>

        {% endfor %}

    </table>
</div>
<div style="padding-left: 3%; position: absolute; bottom: 5%; width: 95%; height: 2.5rem;">
{% for i in available_saved_games %}
    <form method="post" action="{% url 'wolfrollapp:rollFromSaved' i.id %}">
    {% csrf_token %}
    <button type="input" style="vertical-align: center; padding: 12px 24px; background: cadetblue; border-radius: 2px; float: left; font-size: 30px; font-family: Impact; margin-left: auto; margin-right: auto" type="submit">{{ i }}</button>
    </form>
{% endfor %}
</div>


<script>
// When the user clicks on div, open the popup
function myFunction(pk) {
  var popup = document.getElementById(pk);
  popup.classList.toggle("show");
}
</script>
{% endblock %}

wolfrollapp/templates/wolfrollapp/main.html
{%  load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WolfRoller</title>
    <link rel="icon" href="https://cdn.discordapp.com/emojis/900027569204760576.png">
<style>
    *
    {
        padding: 0;
        margin: 0;
    }
    body {

        font-size: 25px;
        background: dimgrey;
    }
    .menu-bar-nav {
        color: burlywood;
        font-family: Bahnschrift;
        padding: 10px;
        padding-top: 25px;

    }
    p {
    color: blanchedalmond;
}
h1 {
    color: blanchedalmond;
}
h2 {
    color: blanchedalmond;
}
td {
    color: blanchedalmond;
}
.role_row {
    nth-of-type(even):
        background-color: rgba(255, 255, 255, 0.1)

}
.wrapper {
    background: dimgrey;
}

.toggle_button {
    border-radius: 100px;
    color: #2196F3;
}
.popup {
  position: relative;
  display: inline-block;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* The actual popup */
.popup .popuptext {
  visibility: hidden;
  width: 450px;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 8px 8px;
  position: absolute;
  z-index: 1;
  bottom: 125%;
  left: 50%;
  margin-left: -225px;
  opacity: 90%;

}

/* Popup arrow */
.popup .popuptext::after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

/* Toggle this class - hide and show the popup */
.popup .show {
  visibility: visible;
  -webkit-animation: fadeIn .4s;
  animation: fadeIn .4s;
}

/* Add animation (fade in the popup) */
@-webkit-keyframes fadeIn {
  from {opacity: 0;}
  to {opacity: 0.9;}
}

@keyframes fadeIn {
  from {opacity: 0;}
  to {opacity:0.9 ;}
}
</style>
</head>


<div style="background: darkslategrey; margin: 0; padding: 0;">
    <span style="color: burlywood; font-size: 32px; padding-left: 2%; font-family: Bahnschrift;"><a href="{% url 'wolfrollapp:home' %}"><img src="https://cdn.discordapp.com/emojis/900027569204760576.png?" style="height:32px; border-radius: 12px;"/></a>Welcome to the pack, {{ request.user }}!</span>
    <table style="float: right;">
        <tr>
            <td>
                <a class="menu-bar-nav" href="{% url 'wolfrollapp:viewRoles' %}">View Roles</a>
            </td>
            <td>
                <a class="menu-bar-nav" href="{% url 'wolfrollapp:editRoles' %}">Edit Roles</a>
            </td>
            <td>
                <a class="menu-bar-nav" href="{% url 'wolfrollapp:logoutPage' %}">Logout</a>
            </td>
        </tr>
    </table>
</div>
<body>
<div class="wrapper">
    {% block content %}
    {% endblock %}
</div>



</body>
</html>

wolfrollapp/templates/wolfrollapp/roles.html
{% extends 'wolfrollapp/main.html' %}
{% block content %}
<div style="padding: 25px; align-content: center">
    <table border=1 frame=void rules=rows>
        <tr>
            <td> </td>
            <td><h2>Role Title</h2></td>
            <td style="width: 100px"><h2>Game Score</h2></td>
            <td style="width: 400px"><h2>Description</h2></td>
            <td><h2>Alignment</h2></td>
            <td><h2>Type</h2></td>
        </tr>
        {% for role in roles_list %}
            <tr class="role_row" style="padding-bottom: 15px">
                <td> </td>
                <td>{{ role.title }}</td>
                <td style="text-align: center">{{  role.score }}</td>
                <td style="width:200px; padding-bottom: 10px">{{ role.description }}</td>
                <td>{{ role.alignment }}</td>
                <td>{{ role.type }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

wolfrollapp/templates/wolfrollapp/rolesEdit.html
{% extends 'wolfrollapp/main.html' %}
{% block content %}
<div style="padding: 25px; align-content: center">
    <table border=1 frame=void rules=rows>
        <tr>
            <td> </td>
            <td><h2>Role Title</h2></td>
            <td style="width: 100px"><h2>Game Score</h2></td>
            <td style="width: 400px"><h2>Description</h2></td>
            <td><h2>Alignment</h2></td>
            <td><h2>Type</h2></td>
        </tr>
        {% for role in roles_list %}
            <tr class="role_row" style="padding-bottom: 15px">
                <td>
                    <form action="{% url 'wolfrollapp:deleteRole' role.title %}" method="POST" name="deleteRole">
                        {% csrf_token %}
                        <button style="vertical-align: center; padding: 8px 12px; background: darkred; border-radius: 40px; float: left; color: blanchedalmond" type="submit">Delete Role</button>
                    </form>
                </td>
                <td>{{ role.title }}</td>
                <td style="text-align: center">{{  role.score }}</td>
                <td style="width:200px; padding-bottom: 10px">{{ role.description }}</td>
                <td style="text-align: center">{{ role.alignment }}</td>
                <td>{{ role.type }}</td>
            </tr>
        {% endfor %}
        <form action="{% url 'wolfrollapp:createRole' %}" method="POST" name="createRole" >
            {% csrf_token %}
            <tr>
            <td></td>
                {% for field in form %}
                    <td>{{ field.label }}</td>
                {% endfor %}
            </tr>
            <tr>
            <td></td>
                {% for field in form %}
                    <td>{{ field }}</td>
                {% endfor %}
            <td><input type="submit" value="Create Role"/></td>
            </tr>
        </form>
    </table>
</div>
{% endblock %}